#!/usr/bin/env bash

set -e

export PATH=env/bin:${PATH}
export DEBUG=true
export IN_TEST=true

echo "--------------"
echo "Running python type checking"
mypy --silent-imports --strict-optional  --warn-no-return --check-untyped-defs management_scheduler
echo "Ok!"

echo "--------------"
echo "Running Flake8 linting"
flake8 management_scheduler --ignore=E128,E501 --exclude="migrations,settings,*/wsgi.py"
echo "Ok!"

echo "--------------"
echo "Running Isort"
isort -rc -c management_scheduler/
echo "Ok!"

echo "--------------"
echo "Running Black"
black management_scheduler/ --check
echo "Ok!"

echo "--------------"
echo "Running django tests"
coverage run --source=management_scheduler --omit='*/wsgi.py,*/settings.py,*/migrations/*.py,*__init__*,*/test*.py,' manage.py test $@
if [[ -z "$@" ]]; then
    coverage report --fail-under=100
    coverage html
fi
